<a onclick="waitSecAndCallAlert()" class="btn btn-primary">Wait 1 sec & Call alert</a>
<br><br>
<a onclick="waitSecAndCallAlertWithLoadingState(this)" class="btn btn-primary">Wait 1 sec & Call alert with loading state
	<span class="lds-dual-ring"></span>
</a>
<br><br>
<a onclick="waitSecAndCallAlertWithClientCallback()" class="btn btn-primary">Wait 1 sec & Call alert with client callback</a>
<br><br>
<a onclick="callCustomCallback()" class="btn btn-primary">call custom callback</a>
<br><br>
<a onclick="callWithClientData()" class="btn btn-primary">call with client data</a>
<br><br>
<a onclick="loadContent()" class="btn btn-primary">load content</a>
<blockquote id="content" class="blockquote">Content field</blockquote>
<br><br>
<a onclick="redirectToMain()" class="btn btn-primary">redirect to main page</a>