<div class="container-fluid">
    <div class="row">
        <div class="col-sm-4 col-md-3 col-lg-2">
            <ul>
                <?php foreach ($log_files as $filename => $basename) { ?>
                    <li><a <?= isset($current_file) && $current_file == $basename ? 'class="selected"' : '' ?> href="<?= c\mvc::getUrl($debugger__DIR__) ?><?= c\input::getLinkParams(['submit' => false, 'url' => false, 'file' => $basename, 'offset' => false]) ?>">
                            <?= $basename ?>
                            <?php if (fileatime($filename) > time() - 3600 * 24 * 3) { ?><span class="badge badge-secondary">!<?php if (fileatime($filename) > time() - 3600 * 24) { ?>!!<?php } ?></span><?php } ?>
                        </a></li>
                <?php } ?>
            </ul>
        </div>
        <div class="col-sm-8 col-md-9 col-lg-10">
            <?php include c\mvc::viewPage() ?>
        </div>
    </div>
</div>